### PR TITLE
Add a rule to disallow mixed named and default exports in ES6.

### PR DESCRIPTION
**Pull request by eventualbuddha**

### CODE REVIEW

**Comment by xjamundx** [comment]
Will get this published tomorrow. Thanks for the contribution!

**Comment by eventualbuddha** [comment]
Ping on the release.

**Comment by xjamundx** [comment]
oh duh. coming...

**Comment by xjamundx** [comment]
`+ eslint-plugin-modules@1.1.0`

**Comment by xjamundx** [comment]
@eventualbuddha you want to help maintain this thing? I can give you repo access and npm rights

**Comment by eventualbuddha** [comment]
Sure, that'd be great.

**Comment by xjamundx** [comment]
@eventualbuddha what's your NPM username? is it the same?

**Comment by eventualbuddha** [comment]
The same.

**Comment by xjamundx** [comment]
`+ eventualbuddha (eslint-plugin-modules)`

**Pull request merged**
